alter table public.tasks add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.tasks alter column user_id set default auth.uid();
drop policy if exists "authenticated users can manage tasks" on public.tasks;
drop policy if exists "users can view own tasks" on public.tasks;
drop policy if exists "users can insert own tasks" on public.tasks;
drop policy if exists "users can update own tasks" on public.tasks;
drop policy if exists "users can delete own tasks" on public.tasks;
create policy "users can view own tasks" on public.tasks for select to authenticated using (auth.uid() = user_id);
create policy "users can insert own tasks" on public.tasks for insert to authenticated with check (auth.uid() = user_id);
create policy "users can update own tasks" on public.tasks for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users can delete own tasks" on public.tasks for delete to authenticated using (auth.uid() = user_id);
create index if not exists tasks_user_id_idx on public.tasks (user_id);
